version: "3"

services:
  postgres:
    image: "postgres:latest"
    ports:
      - 5432:5432
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telemetry
    volumes:
      - ./postgres/:/var/lib/postgresql/data/

  emqx:
    image: "emqx:latest"
    ports:
      - 18083:18083
      - 1883:1883
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  server:
    image: "papaya147/weatherman-telemetry:latest"
    restart: always
    ports:
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MQTT_ENDPOINT: tcp://emqx:1883
      MQTT_USERNAME: admin
      MQTT_PASSWORD: public
      HTTP_PORT: 8080
      POSTGRES_DSN: postgresql://postgres:password@postgres:5432/telemetry?sslmode=disable
      MIGRATION_URL: file://db/migration
