CREATE TABLE IF NOT EXISTS weatherTelemetry(
    millis TIMESTAMPTZ NOT NULL PRIMARY KEY,
    temperature DOUBLE PRECISION NOT NULL,
    humidity DOUBLE PRECISION NOT NULL,
    windSpeed DOUBLE PRECISION NOT NULL,
    windDirection DOUBLE PRECISION NOT NULL,
    pressure DOUBLE PRECISION NOT NULL,
    waterAmount DOUBLE PRECISION NOT NULL
);