// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Weathertelemetry struct {
	Millis        time.Time `json:"millis"`
	Temperature   float64   `json:"temperature"`
	Humidity      float64   `json:"humidity"`
	Windspeed     float64   `json:"windspeed"`
	Winddirection float64   `json:"winddirection"`
	Pressure      float64   `json:"pressure"`
	Wateramount   float64   `json:"wateramount"`
}
