// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	GetWeatherTelemetry(ctx context.Context, millis time.Time) ([]Weathertelemetry, error)
	InsertWeatherTelemetry(ctx context.Context, arg InsertWeatherTelemetryParams) (Weathertelemetry, error)
}

var _ Querier = (*Queries)(nil)
