// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	GetMeanWeatherTelemetry(ctx context.Context, arg GetMeanWeatherTelemetryParams) (GetMeanWeatherTelemetryRow, error)
	GetWeatherTelemetry(ctx context.Context, arg GetWeatherTelemetryParams) ([]Weathertelemetry, error)
	GetWeatherTelemetryByRange(ctx context.Context, arg GetWeatherTelemetryByRangeParams) ([]Weathertelemetry, error)
	InsertWeatherTelemetry(ctx context.Context, arg InsertWeatherTelemetryParams) (Weathertelemetry, error)
}

var _ Querier = (*Queries)(nil)
