// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: weatherTelemetry.sql

package db

import (
	"context"
	"time"
)

const getMeanWeatherTelemetry = `-- name: GetMeanWeatherTelemetry :one
SELECT CAST(
        COALESCE(AVG(temperature), 0) AS DOUBLE PRECISION
    ) AS temperature,
    CAST(COALESCE(AVG(humidity), 0) AS DOUBLE PRECISION) AS humidity,
    CAST(COALESCE(AVG(windSpeed), 0) AS DOUBLE PRECISION) AS windSpeed,
    CAST(
        COALESCE(AVG(windDirection), 0) AS DOUBLE PRECISION
    ) AS windDirection,
    CAST(COALESCE(AVG(pressure), 0) AS DOUBLE PRECISION) AS pressure,
    CAST(
        COALESCE(AVG(waterAmount), 0) AS DOUBLE PRECISION
    ) AS waterAmount
FROM weatherTelemetry
WHERE millis >= $1
    and millis < $2
LIMIT 1
`

type GetMeanWeatherTelemetryParams struct {
	Millis   time.Time `json:"millis"`
	Millis_2 time.Time `json:"millis_2"`
}

type GetMeanWeatherTelemetryRow struct {
	Temperature   float64 `json:"temperature"`
	Humidity      float64 `json:"humidity"`
	Windspeed     float64 `json:"windspeed"`
	Winddirection float64 `json:"winddirection"`
	Pressure      float64 `json:"pressure"`
	Wateramount   float64 `json:"wateramount"`
}

func (q *Queries) GetMeanWeatherTelemetry(ctx context.Context, arg GetMeanWeatherTelemetryParams) (GetMeanWeatherTelemetryRow, error) {
	row := q.db.QueryRow(ctx, getMeanWeatherTelemetry, arg.Millis, arg.Millis_2)
	var i GetMeanWeatherTelemetryRow
	err := row.Scan(
		&i.Temperature,
		&i.Humidity,
		&i.Windspeed,
		&i.Winddirection,
		&i.Pressure,
		&i.Wateramount,
	)
	return i, err
}

const getWeatherTelemetry = `-- name: GetWeatherTelemetry :many
SELECT millis, temperature, humidity, windspeed, winddirection, pressure, wateramount
FROM weatherTelemetry
WHERE millis > $1
ORDER BY millis ASC
LIMIT $2
`

type GetWeatherTelemetryParams struct {
	Millis time.Time `json:"millis"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetWeatherTelemetry(ctx context.Context, arg GetWeatherTelemetryParams) ([]Weathertelemetry, error) {
	rows, err := q.db.Query(ctx, getWeatherTelemetry, arg.Millis, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Weathertelemetry{}
	for rows.Next() {
		var i Weathertelemetry
		if err := rows.Scan(
			&i.Millis,
			&i.Temperature,
			&i.Humidity,
			&i.Windspeed,
			&i.Winddirection,
			&i.Pressure,
			&i.Wateramount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeatherTelemetryByRange = `-- name: GetWeatherTelemetryByRange :many
SELECT millis, temperature, humidity, windspeed, winddirection, pressure, wateramount
FROM weatherTelemetry
WHERE millis >= $1
    AND millis < $2
ORDER BY millis ASC
`

type GetWeatherTelemetryByRangeParams struct {
	Millis   time.Time `json:"millis"`
	Millis_2 time.Time `json:"millis_2"`
}

func (q *Queries) GetWeatherTelemetryByRange(ctx context.Context, arg GetWeatherTelemetryByRangeParams) ([]Weathertelemetry, error) {
	rows, err := q.db.Query(ctx, getWeatherTelemetryByRange, arg.Millis, arg.Millis_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Weathertelemetry{}
	for rows.Next() {
		var i Weathertelemetry
		if err := rows.Scan(
			&i.Millis,
			&i.Temperature,
			&i.Humidity,
			&i.Windspeed,
			&i.Winddirection,
			&i.Pressure,
			&i.Wateramount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWeatherTelemetry = `-- name: InsertWeatherTelemetry :one
INSERT INTO weatherTelemetry(
        millis,
        temperature,
        humidity,
        windSpeed,
        windDirection,
        pressure,
        waterAmount
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING millis, temperature, humidity, windspeed, winddirection, pressure, wateramount
`

type InsertWeatherTelemetryParams struct {
	Millis        time.Time `json:"millis"`
	Temperature   float64   `json:"temperature"`
	Humidity      float64   `json:"humidity"`
	Windspeed     float64   `json:"windspeed"`
	Winddirection float64   `json:"winddirection"`
	Pressure      float64   `json:"pressure"`
	Wateramount   float64   `json:"wateramount"`
}

func (q *Queries) InsertWeatherTelemetry(ctx context.Context, arg InsertWeatherTelemetryParams) (Weathertelemetry, error) {
	row := q.db.QueryRow(ctx, insertWeatherTelemetry,
		arg.Millis,
		arg.Temperature,
		arg.Humidity,
		arg.Windspeed,
		arg.Winddirection,
		arg.Pressure,
		arg.Wateramount,
	)
	var i Weathertelemetry
	err := row.Scan(
		&i.Millis,
		&i.Temperature,
		&i.Humidity,
		&i.Windspeed,
		&i.Winddirection,
		&i.Pressure,
		&i.Wateramount,
	)
	return i, err
}
