// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: weather-telemetry.proto

package weatherdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherTelemetry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp     uint64  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Temperature   float64 `protobuf:"fixed64,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64 `protobuf:"fixed64,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	WindSpeed     float64 `protobuf:"fixed64,4,opt,name=windSpeed,proto3" json:"windSpeed,omitempty"`
	WindDirection float64 `protobuf:"fixed64,5,opt,name=windDirection,proto3" json:"windDirection,omitempty"`
	Pressure      float64 `protobuf:"fixed64,6,opt,name=pressure,proto3" json:"pressure,omitempty"`
	WaterAmount   float64 `protobuf:"fixed64,7,opt,name=waterAmount,proto3" json:"waterAmount,omitempty"`
}

func (x *WeatherTelemetry) Reset() {
	*x = WeatherTelemetry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_weather_telemetry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherTelemetry) ProtoMessage() {}

func (x *WeatherTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_weather_telemetry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherTelemetry.ProtoReflect.Descriptor instead.
func (*WeatherTelemetry) Descriptor() ([]byte, []int) {
	return file_weather_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherTelemetry) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WeatherTelemetry) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherTelemetry) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherTelemetry) GetWindSpeed() float64 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

func (x *WeatherTelemetry) GetWindDirection() float64 {
	if x != nil {
		return x.WindDirection
	}
	return 0
}

func (x *WeatherTelemetry) GetPressure() float64 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *WeatherTelemetry) GetWaterAmount() float64 {
	if x != nil {
		return x.WaterAmount
	}
	return 0
}

var File_weather_telemetry_proto protoreflect.FileDescriptor

var file_weather_telemetry_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2d, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x77, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf0, 0x01, 0x0a, 0x10, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b,
	0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x68,
	0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x53,
	0x70, 0x65, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x77, 0x69, 0x6e, 0x64,
	0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x77, 0x69, 0x6e, 0x64, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x77, 0x69,
	0x6e, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x77, 0x61,
	0x74, 0x65, 0x72, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x77,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_weather_telemetry_proto_rawDescOnce sync.Once
	file_weather_telemetry_proto_rawDescData = file_weather_telemetry_proto_rawDesc
)

func file_weather_telemetry_proto_rawDescGZIP() []byte {
	file_weather_telemetry_proto_rawDescOnce.Do(func() {
		file_weather_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(file_weather_telemetry_proto_rawDescData)
	})
	return file_weather_telemetry_proto_rawDescData
}

var file_weather_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_weather_telemetry_proto_goTypes = []interface{}{
	(*WeatherTelemetry)(nil), // 0: weatherdata.WeatherTelemetry
}
var file_weather_telemetry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weather_telemetry_proto_init() }
func file_weather_telemetry_proto_init() {
	if File_weather_telemetry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_weather_telemetry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeatherTelemetry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_weather_telemetry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weather_telemetry_proto_goTypes,
		DependencyIndexes: file_weather_telemetry_proto_depIdxs,
		MessageInfos:      file_weather_telemetry_proto_msgTypes,
	}.Build()
	File_weather_telemetry_proto = out.File
	file_weather_telemetry_proto_rawDesc = nil
	file_weather_telemetry_proto_goTypes = nil
	file_weather_telemetry_proto_depIdxs = nil
}
