basePath: /
definitions:
  api.publishModel:
    properties:
      humidity:
        example: 50
        type: number
      pressure:
        example: 50
        type: number
      temperature:
        example: 100
        type: number
      topic:
        example: topic/telemetry
        type: string
      water_amount:
        example: 10
        type: number
      wind_direction:
        example: 60
        type: number
      wind_speed:
        example: 25
        type: number
    required:
    - topic
    type: object
  util.ErrorModel:
    properties:
      message:
        example: something went wrong
        type: string
      status:
        example: 400
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: The comprehensive list of all Weatherman Telemetry Server APIs
  title: Weatherman Telemetry Server APIs
  version: "1.0"
paths:
  /data/csv:
    get:
      description: Get a CSV formatted file of all the MQTT data
      produces:
      - text/csv
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorModel'
      summary: Get a CSV formatted file of all the MQTT data
      tags:
      - data
  /publish:
    post:
      description: Mock an MQTT weather publish, fields are formatted as Protobuf
        and sent via the MQTT broker
      parameters:
      - description: json
        in: body
        name: request-body
        required: true
        schema:
          $ref: '#/definitions/api.publishModel'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.publishModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorModel'
      summary: Mock an MQTT weather publish
      tags:
      - mqtt
swagger: "2.0"
